[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DESP32S3_BOARD
    -DCONFIG_ESP32S3_SPIRAM
    -DCONFIG_SPIRAM_MODE_QUAD
    -O2
    -Wall
    -Wextra
    -Wpedantic
    -std=c++17
lib_deps =
test_framework = unity

[env:testing]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Wpedantic
